import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import { Clock, MapPin, Calendar, Sparkles } from "lucide-react";

interface Activity {
  title: string;
  description: string;
  image: string | null;
  lat: number;
  lng: number;
  timeOfDay: "Morning" | "Afternoon" | "Evening";
}

interface Day {
  day: number;
  title: string;
  activities: Activity[];
}

interface ItineraryData {
  destination: string;
  days: Day[];
}

export default async function PrintItineraryPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = await params;
  const itinerary = await prisma.itinerary.findUnique({
    where: { id: resolvedParams.id },
  });

  if (!itinerary || !itinerary.data) {
    notFound();
  }

  const data = itinerary.data as unknown as ItineraryData;

  // Use the first activity's image for the cover, or a fallback color if none exists
  const coverImage = data.days[0]?.activities[0]?.image || null;

  return (
    <div className="bg-[#f9f6f0] min-h-screen text-[#1a1a1a] font-sans print:p-0 print:m-0 print:max-w-none w-[210mm] mx-auto">
      
      {/* =========================================================================
          PAGE 1: COVER
      ========================================================================= */}
      <div className="relative h-[297mm] flex flex-col p-12 overflow-hidden break-after-page">
        {coverImage ? (
          <>
            <img src={coverImage} alt="Cover" className="absolute inset-0 w-full h-full object-cover grayscale-[40%] brightness-50" />
            <div className="absolute inset-0 bg-black/40"></div>
          </>
        ) : (
          <div className="absolute inset-0 bg-[#111827]"></div>
        )}

        <div className="relative z-10 flex-1 flex flex-col justify-between h-full">
          {/* Top Badge */}
          <div className="self-start px-3 py-1.5 bg-black/50 backdrop-blur-md border-l-2 border-[#b54a2a] flex items-center gap-2">
            <Sparkles className="w-3 h-3 text-white/70" />
            <span className="text-[9px] font-medium tracking-[0.2em] text-white/90 uppercase">
              Generated by NomadGo
            </span>
          </div>

          {/* Main Title Area */}
          <div className="mt-auto mb-16">
            <h1 className="text-8xl font-serif text-white tracking-tight leading-[0.8] mb-6 uppercase">
              {itinerary.destination}
            </h1>
            
            <div className="flex items-center gap-4 text-[10px] font-bold tracking-[0.2em] text-white/80 uppercase">
              <span>{itinerary.days} DAYS</span>
              <span className="w-1.5 h-1.5 bg-[#b54a2a]"></span>
              <span>{itinerary.vibe} VIBE</span>
              <span className="w-1.5 h-1.5 bg-[#b54a2a]"></span>
              <span>{itinerary.budget} BUDGET</span>
            </div>

            <div className="w-16 h-px bg-[#b54a2a] my-8"></div>

            <div className="space-y-1 text-white/60 font-serif italic text-sm">
              <p>V.01</p>
              <p>Curated Edition</p>
            </div>
          </div>
        </div>
      </div>

      {/* =========================================================================
          PAGE 2: SUMMARY & LOGISTICS
      ========================================================================= */}
      <div className="h-[297mm] p-12 break-after-page relative">
        <p className="text-[9px] font-bold tracking-[0.2em] text-[#b54a2a] uppercase mb-4">Preparation</p>
        <h2 className="text-5xl font-serif font-bold text-[#1a1a1a] leading-tight mb-4 max-w-sm">
          Summary & Logistics
        </h2>
        <div className="w-24 h-px bg-slate-300 mb-16"></div>

        <div className="flex gap-12">
          {/* Left Column */}
          <div className="flex-1 bg-white p-8 border border-slate-100 shadow-sm">
            <h3 className="text-xl font-serif font-bold mb-8">Trip Protocol</h3>
            
            <div className="space-y-8">
              <div className="flex gap-4">
                <div className="w-8 h-8 bg-slate-900 flex items-center justify-center flex-shrink-0">
                  <MapPin className="w-4 h-4 text-white" />
                </div>
                <div>
                  <h4 className="text-sm font-bold mb-1">Destination Focus</h4>
                  <p className="text-xs text-slate-500 leading-relaxed">
                    This itinerary has been specifically tailored to a {itinerary.vibe.toLowerCase()} experience, focusing on activities that align with this energy over the next {itinerary.days} days.
                  </p>
                </div>
              </div>
              
              <div className="flex gap-4">
                <div className="w-8 h-8 bg-slate-100 flex items-center justify-center flex-shrink-0">
                  <Clock className="w-4 h-4 text-slate-900" />
                </div>
                <div>
                  <h4 className="text-sm font-bold mb-1">Pacing</h4>
                  <p className="text-xs text-slate-500 leading-relaxed">
                    Designed to ensure you experience the essential highlights without feeling rushed. Adjust timings locally based on personal preference.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column (Vitals Black Box) */}
          <div className="w-64 bg-[#0a0a0a] text-white p-8 flex flex-col gap-8">
            <div>
              <p className="text-[8px] tracking-[0.2em] uppercase text-slate-500 mb-1">Duration</p>
              <p className="text-sm font-bold">{itinerary.days} Full Days</p>
            </div>
            <div className="h-px bg-white/10"></div>
            <div>
              <p className="text-[8px] tracking-[0.2em] uppercase text-slate-500 mb-1">Vibe</p>
              <p className="text-sm font-bold uppercase">{itinerary.vibe}</p>
            </div>
            <div className="h-px bg-white/10"></div>
            <div>
              <p className="text-[8px] tracking-[0.2em] uppercase text-slate-500 mb-1">Budget Strategy</p>
              <p className="text-sm font-bold uppercase">{itinerary.budget}</p>
            </div>
          </div>
        </div>

        {/* Essential Protocol (Bottom Left) */}
        <div className="mt-16 max-w-sm pl-6 border-l-2 border-[#b54a2a]">
          <h3 className="text-lg font-serif font-bold mb-4">Essential Notes</h3>
          <div className="space-y-4">
            <p className="text-xs text-slate-600 leading-relaxed">
              <span className="font-bold text-[#b54a2a] mr-2">01</span>
              Review all activities and cross-reference opening hours, as they may shift due to local holidays.
            </p>
            <p className="text-xs text-slate-600 leading-relaxed">
              <span className="font-bold text-[#b54a2a] mr-2">02</span>
              This document is designed to be your primary offline reference. Ensure you have downloaded offline maps.
            </p>
          </div>
        </div>
      </div>

      {/* =========================================================================
          PAGE 3+: ITINERARY DAYS
      ========================================================================= */}
      {data.days.map((day, dayIndex) => (
        <div key={day.day} className="p-12 break-before-page min-h-[297mm] relative">
          
          {/* Day Header */}
          <div className="mb-16 border-b border-[#b54a2a] pb-6 flex justify-between items-end">
            <div>
              <p className="text-[8px] font-bold tracking-[0.2em] text-[#b54a2a] uppercase mb-2">
                Itinerary Chapter {day.day}
              </p>
              <h2 className="text-6xl font-serif text-[#1a1a1a] tracking-tight">
                DAY {String(day.day).padStart(2, '0')}
              </h2>
            </div>
            <h3 className="text-2xl font-serif italic text-slate-500 text-right max-w-[250px] leading-tight">
              {day.title}
            </h3>
          </div>

          {/* Quote Block */}
          <div className="pl-6 border-l-4 border-[#b54a2a] mb-20 max-w-2xl">
            <p className="text-xl font-serif text-[#1a1a1a] leading-relaxed">
              "Embrace the rhythm of {itinerary.destination} on Day {day.day}. We explore the intersections of {itinerary.vibe.toLowerCase()} experiences tailored uniquely for you."
            </p>
          </div>

          {/* Activities Flow */}
          <div className="space-y-16 relative">
            {day.activities.map((activity, actIndex) => {
              const isEven = actIndex % 2 === 0;

              return (
                <div key={actIndex} className="break-inside-avoid relative">
                  
                  {/* Connecting Line to next activity (if not last) */}
                  {actIndex < day.activities.length - 1 && (
                    <div className="absolute left-1/2 -bottom-16 w-px h-16 bg-slate-300 -translate-x-1/2 flex items-center justify-center">
                      <div className="w-5 h-5 bg-white border border-slate-300 rounded-full flex items-center justify-center">
                        <MapPin className="w-2.5 h-2.5 text-slate-400" />
                      </div>
                    </div>
                  )}

                  <div className={`flex flex-col ${isEven ? 'md:flex-row' : 'md:flex-row-reverse'} gap-12 items-center`}>
                    
                    {/* Text Block */}
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <span className="text-[10px] font-bold tracking-widest text-[#1a1a1a]">
                          {activity.timeOfDay === "Morning" ? "09:00 AM" : activity.timeOfDay === "Afternoon" ? "02:00 PM" : "07:00 PM"}
                        </span>
                        <span className="px-2 py-0.5 bg-slate-200 text-[8px] font-bold tracking-widest text-slate-500 uppercase">
                          {activity.timeOfDay}
                        </span>
                      </div>
                      
                      <div className="pl-4 border-l-2 border-[#b54a2a]">
                        <h4 className="text-3xl font-serif text-[#1a1a1a] mb-4">
                          {activity.title}
                        </h4>
                        <p className="text-xs font-sans text-slate-600 leading-relaxed">
                          {activity.description}
                        </p>
                      </div>
                    </div>

                    {/* Image Block */}
                    <div className="flex-1 w-full">
                      {activity.image ? (
                        <div className="aspect-[4/3] w-full bg-slate-200">
                          <img 
                            src={activity.image} 
                            alt={activity.title} 
                            className="w-full h-full object-cover filter contrast-125 saturate-50"
                          />
                        </div>
                      ) : (
                        <div className="aspect-[4/3] w-full border border-slate-200 bg-white flex items-center justify-center">
                           <span className="text-xs font-serif text-slate-400 italic">No image available</span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Footer for the page */}
          <div className="absolute bottom-12 left-12 right-12">
             <div className="w-full h-[60px] bg-[#0f172a] text-center flex flex-col justify-center text-white/50 space-y-2">
                <p className="text-[10px] font-serif font-bold tracking-[0.2em] italic text-white/80 uppercase">The {itinerary.destination} Editorial</p>
                <p className="text-[6px] tracking-[0.2em] uppercase">© {new Date().getFullYear()} NomadGo. All rights reserved. Printed Digitally.</p>
             </div>
          </div>

        </div>
      ))}

    </div>
  );
}
